### ISSUE TITLE
Uncaught exception with message '401: unauthenticated request'

### ISSUE THREAD

**Issue by trashish** [stepansib/alm-client#2]
I'm getting: 
[Tue Aug 02 23:59:58.669737 2016] [:error] [pid 8323] [client 2.233.167.197:50172] PHP Fatal error:  Uncaught exception 'StepanSib\AlmClient\Exception\AlmCurlException' with message '401: unauthenticated request' in /XXXX/vendor/stepansib/alm-client/src/AlmCurl.php:136\nStack trace:\n#0 /XXX/vendor/stepansib/alm-client/src/AlmEntityParametersManager.php(133): StepanSib\AlmClient\AlmCurl->exec('https://group.t...')\n#1 /XXXX/vendor/stepansib/alm-client/src/AlmEntityParametersManager.php(43): StepanSib\AlmClient\AlmEntityParametersManager->refreshLists()\n#2 /XXX/example/lists.php(15): StepanSib\AlmClient\AlmEntityParametersManager->getLists()\n#3 {main}\n  thrown in /XXX/vendor/stepansib/alm-client/src/AlmCurl.php on line 136

Client is on
Linux Ubuntu-1410-utopic-64-minimal 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Server is 12.21.64

**Comment by stepansib** [comment]
401: unauthenticated request - means that you provided wrong LDAP credentials.
Maybe you trying to execute operation that not allowed to your LDAP user. 
Try to check this operation in HP ALM/QC frontend first
